const TMDB_W500 = 'https://image.tmdb.org/t/p/w500';
const TMDB_W185 = 'https://image.tmdb.org/t/p/w185';
const TMDB_ORIG = 'https://image.tmdb.org/t/p/original';

export const FALLBACK_POSTER = 'https://via.placeholder.com/300x450/181924/6b7280?text=No+Image';
export const FALLBACK_BACKDROP = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1920 520"%3E%3Crect fill="%230b0c10" width="1920" height="520"/%3E%3C/svg%3E';
export const FALLBACK_FACE = 'https://via.placeholder.com/80x80/181924/6b7280?text=?';

export const MOCK_MOVIES = [
  {
    id: 1,
    title: "Kalki 2898 AD",
    genre: ["Action", "Sci-Fi", "Adventure"],
    language: "Telugu, Hindi, English",
    duration: "2h 56m",
    ageRating: "UA 13+",
    rating: 8.7,
    tomatometer: "92%",
    description: "A glimpse into the future of 2898 AD. When darkness threatens to consume the world, a savior rises.",
    posterUrl: `${TMDB_W500}/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg`,
    backdropUrl: `${TMDB_ORIG}/o8XSR1SONnjcsv84NRu6Mwsl5io.jpg`,
    trailerUrl: "https://www.youtube.com/embed/y1-w1kUGuz8",
    trending: true,
    featured: true,
  },
  {
    id: 2,
    title: "Deadpool & Wolverine",
    genre: ["Action", "Comedy", "Sci-Fi"],
    language: "English",
    duration: "2h 08m",
    ageRating: "A",
    rating: 8.3,
    tomatometer: "79%",
    description: "A listless Wade Wilson must reluctantly suit-up again with an even more reluctant Wolverine.",
    posterUrl: `${TMDB_W500}/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg`,
    backdropUrl: `${TMDB_ORIG}/cOoVcVQ3i1m5b2xtqKBtoTSbxC1.jpg`,
    trailerUrl: "https://www.youtube.com/embed/73_1biulkYk",
    trending: true,
    featured: false,
  },
  {
    id: 3,
    title: "Furiosa: A Mad Max Saga",
    genre: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
    duration: "2h 28m",
    ageRating: "A",
    rating: 8.1,
    tomatometer: "90%",
    description: "The origin story of renegade warrior Furiosa before her encounter with Mad Max.",
    posterUrl: `${TMDB_W500}/iADOJ8Zymht2JPMoy3R7xceZprc.jpg`,
    backdropUrl: `${TMDB_ORIG}/raph7qjAGTMXaIjVxt6ZDSXRzUr.jpg`,
    trailerUrl: "https://www.youtube.com/embed/XJMuhwVlca4",
    trending: true,
    featured: false,
  },
  {
    id: 4,
    title: "Inside Out 2",
    genre: ["Animation", "Comedy", "Family"],
    language: "English",
    duration: "1h 36m",
    ageRating: "U",
    rating: 8.6,
    tomatometer: "91%",
    description: "Follow Riley in her teenage years as new emotions storm Headquarters.",
    posterUrl: `${TMDB_W500}/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg`,
    backdropUrl: `${TMDB_ORIG}/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg`,
    trailerUrl: "https://www.youtube.com/embed/LEjhY15eCx0",
    trending: true,
    featured: false,
  },
  {
    id: 5,
    title: "Dune: Part Two",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    language: "English",
    duration: "2h 46m",
    ageRating: "UA 16+",
    rating: 8.9,
    tomatometer: "93%",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    posterUrl: `${TMDB_W500}/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg`,
    backdropUrl: `${TMDB_ORIG}/eZ239CUp1d6OryZEBPnO2n87gMG.jpg`,
    trailerUrl: "https://www.youtube.com/embed/Way9Dexny3w",
    trending: true,
    featured: false,
  },
  {
    id: 6,
    title: "Godzilla x Kong: The New Empire",
    genre: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
    duration: "1h 55m",
    ageRating: "UA 13+",
    rating: 7.8,
    tomatometer: "54%",
    description: "Godzilla and Kong clash in an epic battle as humans unravel their intertwined origins.",
    posterUrl: `${TMDB_W500}/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg`,
    backdropUrl: `${TMDB_ORIG}/gvLG3Fnznkxl4SmYfcK8gUuqxM8.jpg`,
    trailerUrl: "https://www.youtube.com/embed/lV1OOlGwExM",
    trending: true,
    featured: false,
  },
  {
    id: 7,
    title: "Twisters",
    genre: ["Action", "Thriller", "Adventure"],
    language: "English",
    duration: "2h 02m",
    ageRating: "UA 13+",
    rating: 7.6,
    tomatometer: "75%",
    description: "Storm chasers brave tornado alley in the most dangerous season on record.",
    posterUrl: `${TMDB_W500}/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg`,
    backdropUrl: `${TMDB_ORIG}/58D6ZAvOKxlHjyX9S8qNKSBE9Y.jpg`,
    trailerUrl: "https://www.youtube.com/embed/wdok0rZdmx4",
    trending: true,
    featured: false,
  },
  {
    id: 8,
    title: "Kingdom of the Planet of the Apes",
    genre: ["Action", "Sci-Fi", "Adventure"],
    language: "English",
    duration: "2h 25m",
    ageRating: "UA 13+",
    rating: 7.9,
    tomatometer: "80%",
    description: "Many years after Caesar's reign, a young ape undertakes a harrowing journey that will define the future.",
    posterUrl: `${TMDB_W500}/gKkl37BQuKTanygYQG1pyYgLVgf.jpg`,
    backdropUrl: `${TMDB_ORIG}/fypydCipcWDKDTTCoPucBsdGYXW.jpg`,
    trailerUrl: "https://www.youtube.com/embed/XtFI7SNtVpY",
    trending: true,
    featured: false,
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: 'success',
    icon: '🎟️',
    title: 'Booking Confirmed!',
    body: 'Interstellar Odyssey – 3 seats confirmed.',
    time: '2m ago',
    read: false,
  },
  {
    id: 2,
    type: 'info',
    icon: '🎬',
    title: 'New Movie Added',
    body: 'The Last Horizon is now available for booking.',
    time: '1h ago',
    read: false,
  },
  {
    id: 3,
    type: 'warning',
    icon: '⏰',
    title: 'Show in 2 Hours',
    body: "Don't forget! Crimson Shadows starts at 7:00 PM.",
    time: '30m ago',
    read: true,
  },
];

export const DEFAULT_CAST_MAP = {
  1: [
    { name: "Prabhas", role: "Bhairava", profileUrl: `${TMDB_W185}/xW120Cef6K0yQJ4eF74Wk345H12.jpg` },
    { name: "Amitabh Bachchan", role: "Ashwatthama", profileUrl: `${TMDB_W185}/7C24b7vRzQk947tF234H917.jpg` },
    { name: "Kamal Haasan", role: "Supreme Yaskin", profileUrl: `${TMDB_W185}/v60WlB532J47H100Y918.jpg` },
    { name: "Deepika Padukone", role: "SUM-80", profileUrl: `${TMDB_W185}/120HkQJz92837f61.jpg` },
    { name: "Disha Patani", role: "Roxie", profileUrl: `${TMDB_W185}/8942HjKz2934.jpg` },
  ],
  2: [
    { name: "Ryan Reynolds", role: "Wade Wilson / Deadpool", profileUrl: `${TMDB_W185}/2hsuobGevKwB23eYvWf16ieYpYh.jpg` },
    { name: "Hugh Jackman", role: "Logan / Wolverine", profileUrl: `${TMDB_W185}/5H60o6j0H600.jpg` },
    { name: "Emma Corrin", role: "Cassandra Nova", profileUrl: `${TMDB_W185}/43985Hj0.jpg` },
    { name: "Morena Baccarin", role: "Vanessa", profileUrl: `${TMDB_W185}/74839Hj.jpg` },
  ],
  5: [
    { name: "Timothée Chalamet", role: "Paul Atreides", profileUrl: `${TMDB_W185}/be123Hj0.jpg` },
    { name: "Zendaya", role: "Chani", profileUrl: `${TMDB_W185}/4839Hj1.jpg` },
    { name: "Rebecca Ferguson", role: "Lady Jessica", profileUrl: `${TMDB_W185}/8392Hj2.jpg` },
    { name: "Javier Bardem", role: "Stilgar", profileUrl: `${TMDB_W185}/9482Hj3.jpg` },
  ],
};

export const DEFAULT_THEATRES = [
  { id: 101, name: "PVR: Orion Mall, Rajajinagar", location: "Rajajinagar, Bengaluru", rating: 4.6, dist: "2.1 km", status: "filling", statusText: "Filling Fast", amenities: ["IMAX", "4DX", "Dolby Atmos", "Recliners", "Food Court", "Parking"] },
  { id: 102, name: "INOX: Mantri Square Mall", location: "Malleswaram, Bengaluru", rating: 4.5, dist: "3.8 km", status: "available", statusText: "Available", amenities: ["Dolby Atmos", "Recliners", "Parking"] },
  { id: 103, name: "Cinepolis: ETA Mall, Magadi Road", location: "Magadi Road, Bengaluru", rating: 4.4, dist: "4.2 km", status: "full", statusText: "Almost Full", amenities: ["VIP Lounge", "Dolby Atmos", "Food Court"] },
  { id: 104, name: "PVR: Phoenix Marketcity", location: "Whitefield, Bengaluru", rating: 4.7, dist: "6.0 km", status: "available", statusText: "Available", amenities: ["IMAX", "Dolby Atmos", "Recliners", "Parking", "Food Court"] },
];

export const MOCK_OFFERS = [
  { id: 'OFFER100', code: 'WELCOME100', title: 'Flat ₹100 Off on First Booking', desc: 'Use code WELCOME100 on your first movie ticket purchase.', validTill: '31 Dec 2026', discount: 100 },
  { id: 'OFFER50', code: 'BANK50', title: '50% Cashback up to ₹150', desc: 'Valid on HDFC & ICICI Credit/Debit cards.', validTill: '15 Nov 2026', discount: 150 },
  { id: 'OFFERBOGO', code: 'BOGO2026', title: 'Buy 1 Get 1 Free Ticket', desc: 'Applicable on weekend shows for select theatres.', validTill: '30 Aug 2026', discount: 200 },
];

export const MOCK_BOOKINGS = [
  {
    id: "BMS-982341",
    movieTitle: "Dune: Part Two",
    posterUrl: `${TMDB_W500}/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg`,
    theatreName: "PVR Orion Mall",
    screenName: "Screen 3",
    showTime: "07:30 PM",
    showDate: "Today",
    seats: ["C5", "C6"],
    totalAmount: 834,
    status: "Confirmed",
    qrCode: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=BMS-982341",
  },
  {
    id: "BMS-871239",
    movieTitle: "Kalki 2898 AD",
    posterUrl: `${TMDB_W500}/rstcAnBeCkxNQjNp3YXrF6IP1tW.jpg`,
    theatreName: "INOX Mantri Square",
    screenName: "IMAX Screen 1",
    showTime: "04:15 PM",
    showDate: "18 Jul 2026",
    seats: ["D10", "D11", "D12"],
    totalAmount: 1250,
    status: "Completed",
    qrCode: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=BMS-871239",
  }
];
